version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:jdk-node
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-modules-v1-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-modules-v1-{{ arch }}-{{ .Branch }}
            - node-modules-v1-{{ arch }}
      - run: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: node-modules-v1-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm run build
      - persist_to_workspace:
          root: doc
          paths:
            - index.html
    docs-deploy:
      docker:
        - image: node:8.10.0
      steps:
        - checkout
        - attach_workspace:
            at: doc
        - run:
            name: Install and configure dependencies
            command: |
              npm install -g --silent gh-pages@2.2.0
              git config user.email "ci-build@circleci.com"
              git config user.name "ci-build"
        - run:
            name: Deploy docs to gh-pages branch
            command: gh-pages --dist doc

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - docs-deploy:
          requires:
            - build
          filters:
            branches:
              only: master
