version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:13.0-node
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-modules-v1-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-modules-v1-{{ arch }}-{{ .Branch }}
            - node-modules-v1-{{ arch }}
      - run: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: node-modules-v1-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - doc/index.html
            - lib/*
  docs-deploy:
    docker:
      - image: cimg/node:14.0
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.2.0
            git config user.email "ci-build@circleci.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "44:14:f3:41:45:06:1c:19:c8:73:03:bd:75:ec:07:c1"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist build/doc --message "[skip ci] Update doc pages"
  npm-deploy:
    docker:
      - image: cimg/node:14.0
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run:
          name: move package files to expected location
          command: cp -r build/lib .
      - run:
          name: publish package
          command: npm publish

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - docs-deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - approve-npm:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - npm-deploy:
          requires:
            - build
            - approve-npm
          filters:
            branches:
              only: master
